/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesforce_data_exporter;

import static salesforce_data_exporter.Login.sObj;

import com.sforce.ws.ConnectionException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Afzy
 */
public class FileExportComplete extends javax.swing.JFrame {

    /**
     * Creates new form FileExportComplete
     */
    public FileExportComplete() {
        initComponents();
        //QuerySalesforce.csvFile="Sample data/Sample data/Sample data/Sample data";
        this.tFieldPath.setText(QuerySalesforce.csvFile);
        //lMessage.setText( "<html><b>"+lMessage.getText() + "</b><p>"+QuerySalesforce.csvFile+"</p></html>");
        this.lNumberOfRecords.setText(this.lNumberOfRecords.getText() + SQueryResultFields.iTotalNumberofRecordExported);
        this.lbatchFailed.setText(this.lbatchFailed.getText()+SQueryResultFields.listFailed.size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lMessage = new javax.swing.JLabel();
        bLogout = new javax.swing.JButton();
        dExportAnotherFile = new javax.swing.JButton();
        lNumberOfRecords = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tFieldPath = new javax.swing.JTextArea();
        lbatchFailed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lMessage.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lMessage.setText("Export file path:");
        lMessage.setToolTipText("Export file path:" + SQueryResultFields.sFilePath);
        lMessage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lMessage.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lMessage.setOpaque(true);
        lMessage.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        bLogout.setText("Logout");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        dExportAnotherFile.setText("Export More..");
        dExportAnotherFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dExportAnotherFileActionPerformed(evt);
            }
        });

        lNumberOfRecords.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lNumberOfRecords.setText("Number of records exported: ");

        tFieldPath.setEditable(false);
        tFieldPath.setColumns(20);
        tFieldPath.setRows(5);
        jScrollPane1.setViewportView(tFieldPath);
        tFieldPath.getAccessibleContext().setAccessibleDescription("");

        lbatchFailed.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lbatchFailed.setText("Number of records failed to query: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbatchFailed)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lNumberOfRecords)
                        .addGap(385, 385, 385))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dExportAnotherFile)
                                .addGap(28, 28, 28)
                                .addComponent(bLogout))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(lNumberOfRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbatchFailed)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dExportAnotherFile)
                    .addComponent(bLogout))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        try {
            // TODO add your handling code here:
            Main.logout();
        } catch (ConnectionException ex) {
            Logger.getLogger(FileExportComplete.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_bLogoutActionPerformed

    private void dExportAnotherFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dExportAnotherFileActionPerformed
        // TODO add your handling code here:
        SQueryResultFields.exportComplete.setVisible(false);
        sObj = new SObjectSelection();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        sObj.setLocation(dim.width / 2 - sObj.getSize().width / 2, dim.height / 2 - sObj.getSize().height / 2);
        sObj.setTitle("Object List");
        sObj.setVisible(true);
    }//GEN-LAST:event_dExportAnotherFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileExportComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileExportComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileExportComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileExportComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileExportComplete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogout;
    private javax.swing.JButton dExportAnotherFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lMessage;
    private javax.swing.JLabel lNumberOfRecords;
    private javax.swing.JLabel lbatchFailed;
    private javax.swing.JTextArea tFieldPath;
    // End of variables declaration//GEN-END:variables
}
