/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesforce_data_exporter;

//import com.sforce.soap.enterprise.DescribeTab;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Afzy
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static Login loginScreen;
    public static SObjectSelection sObj;
    
    private final String sEndPointURLError="Please enter End Point URL";
    private final String sUserNameError="Please enter User Name";
    private final String sPasswordError="Please enter Password";
    private final String sBlank="";
    private final String sObjectFieldTitle="Select Object";
    private static final String sLogin="Login";

    public Login() {

        initComponents();
        this.tEndPointURl.setVisibleRowCount(1);
        this.tEndPointURl.setSelectedIndex(0);
        this.tAPIVersion.setText("39.0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lUserName = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lMessage = new javax.swing.JLabel();
        dUserName = new javax.swing.JTextField();
        lEndPointURL = new javax.swing.JLabel();
        bLogin = new javax.swing.JButton();
        dPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        tAPIVersion = new javax.swing.JTextField();
        lAPIVersion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tEndPointURl = new javax.swing.JList<>();
        ctraceFlag = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));

        lUserName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lUserName.setText("User Name:");
        lUserName.setToolTipText("Salesforce User Name");
        lUserName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lPassword.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lPassword.setText("Password + Security Token:");

        lMessage.setForeground(new java.awt.Color(204, 0, 0));
        lMessage.setAutoscrolls(true);
        lMessage.setMaximumSize(new java.awt.Dimension(100, 10));
        lMessage.setPreferredSize(new java.awt.Dimension(500, 200));
        lMessage.setSize(new java.awt.Dimension(500, 20));

        dUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dUserNameActionPerformed(evt);
            }
        });

        lEndPointURL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lEndPointURL.setText("Organization Type");

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Salesforce File Search");
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tAPIVersion.setToolTipText("Eg: 39.0");

        lAPIVersion.setText("API version");

        tEndPointURl.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "SandBox", "Production" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tEndPointURl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tEndPointURl);

        ctraceFlag.setText("Trace Payload");
        ctraceFlag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctraceFlagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPassword)
                            .addComponent(lUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lEndPointURL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lAPIVersion))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tAPIVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(ctraceFlag))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                .addComponent(dUserName))))
                    .addComponent(lMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(bLogin)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lUserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPassword)
                            .addComponent(dPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lEndPointURL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAPIVersion)
                    .addComponent(tAPIVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctraceFlag))
                .addGap(18, 18, 18)
                .addComponent(bLogin)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        
        lMessage.setText(sBlank);
        lMessage.setToolTipText(sBlank);
        Main.sTraceTraffic = this.ctraceFlag.isSelected();
        String sEndPointURL=null;
        if (salesforce_data_exporter.Main.connectionError!=null && !salesforce_data_exporter.Main.connectionError.isEmpty()) 
            salesforce_data_exporter.Main.connectionError = null;
        salesforce_data_exporter.Main.connectionError = sBlank;
        if (!dUserName.getText().isEmpty()) {
            salesforce_data_exporter.Main.USERNAME = dUserName.getText();
            if (dPassword.getPassword().length != 0) {
                System.out.println("Pass" + String.valueOf(dPassword.getPassword()));
                salesforce_data_exporter.Main.PASSWORD = String.valueOf(dPassword.getPassword());
                if (!tEndPointURl.getSelectedValue().isEmpty()) {
                    if(tEndPointURl.getSelectedValue().equals("SandBox"))
                         sEndPointURL =  "https://test.salesforce.com";
                    else
                         sEndPointURL =  "https://login.salesforce.com";
                    if(!this.tAPIVersion.getText().isEmpty())
                    {
                        System.out.println("sEndPointURL:"+sEndPointURL);
                        salesforce_data_exporter.Main.ENDPOINTURL = sEndPointURL+"/services/Soap/u/"+this.tAPIVersion.getText();
                    }
                    else
                    {
                       lMessage.setText("Enter API version before clicking Login button"); 
                    }
                }
                else
                {
                    lMessage.setText("Select Org firs and click Login button.");
                }
            } else {
                lMessage.setText(sPasswordError);
                dPassword.grabFocus();
            }
        } else {
            lMessage.setText(sUserNameError);
            dUserName.grabFocus();
        }

        if (lMessage.getText().length() == 0) 
        {
            try {
                salesforce_data_exporter.Main.main(null);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (!salesforce_data_exporter.Main.connectionError.isEmpty()) 
            {
                lMessage.setText( salesforce_data_exporter.Main.connectionError );
                lMessage.setToolTipText(lMessage.getText());
            } else 
            {
                loginScreen.setVisible(false);
                sObj = new SObjectSelection();
                
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                sObj.setLocation(dim.width / 2 - sObj.getSize().width / 2, dim.height / 2 - sObj.getSize().height / 2);
                sObj.setTitle(sObjectFieldTitle);
                sObj.setVisible(true);

                //new SObjectSelection().setVisible(true);
            }
        }

    }//GEN-LAST:event_bLoginActionPerformed

    private void dUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dUserNameActionPerformed

    private void ctraceFlagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctraceFlagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctraceFlagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                loginScreen = new Login();
                loginScreen.setPreferredSize(loginScreen.getPreferredSize());
                System.out.println(loginScreen.lMessage.getPreferredSize());
                loginScreen.dUserName.setPreferredSize(loginScreen.dUserName.getPreferredSize());
                loginScreen.dPassword.setPreferredSize(loginScreen.dPassword.getPreferredSize());
                //loginScreen.dEndPointURL.setPreferredSize(loginScreen.dEndPointURL.getPreferredSize());
                loginScreen.lMessage.setPreferredSize(loginScreen.lMessage.getPreferredSize());
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                loginScreen.setLocation(dim.width / 2 - loginScreen.getSize().width / 2, dim.height / 2 - loginScreen.getSize().height / 2);
                loginScreen.setTitle(sLogin);
                loginScreen.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JCheckBox ctraceFlag;
    private javax.swing.JPasswordField dPassword;
    private javax.swing.JTextField dUserName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAPIVersion;
    private javax.swing.JLabel lEndPointURL;
    private javax.swing.JLabel lMessage;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUserName;
    private javax.swing.JTextField tAPIVersion;
    private javax.swing.JList<String> tEndPointURl;
    // End of variables declaration//GEN-END:variables
}
